// Export all section components
export { SlideshowHero } from './SlideshowHero'
export { IconBar } from './IconBar'
export { ImageWithText } from './ImageWithText'
export { FeaturedCollection } from './FeaturedCollection'
export { Testimonials } from './Testimonials'
export { Newsletter } from './Newsletter'
export { ComparisonTable } from './ComparisonTable'
export { ContactForm } from './ContactForm'
export { Multicolumn } from './Multicolumn'
export { VideoSection } from './VideoSection'
